### ISSUE TITLE
Renaming Repo

### ISSUE THREAD

**Issue by schmijos** [coredump-ch/coredumpbot#3]
Would you mind to rename the repo to something more specific (e.g.: _telebot_)?

**Comment by dbrgn** [comment]
Why? :)

Alternatively to _telebot_, what about _telegram-bot_ or _coredumpbot-telegram_?

Btw, we already have an IRC bot: https://github.com/coredump-ch/moss

**Comment by schmijos** [comment]
Because _coredumpbot_ is too general for a telegram bot.

**Comment by rnestler** [comment]
I propose _teledump_ or _coregram_ :wink: or _CoDuTeBo_. Maybe just _Roy_, _Jen_ or _Richmond_?

**Comment by dbrgn** [comment]
We just discussed this, and decided that we could add multiple backends (Telegram, IRC, Jabber). So we'll leave it at _coredumpbot_.

Regarding _teledump_ and _coregram_, that doesn't work because Telegram forces the bot name to end in `bot`.

I'll close this for now, please re-open if you disagree :)
